export const elementConstructors = new Map<string, typeof HTMLElement>([
	['a', window.HTMLAnchorElement],
	['blockquote', window.HTMLQuoteElement],
	['br', window.HTMLBRElement],
	['caption', window.HTMLTableCaptionElement],
	['col', window.HTMLTableColElement],
	['colgroup', window.HTMLTableColElement],
	['datalist', window.HTMLDataListElement],
	['del', window.HTMLModElement],
	// ['dir', window.HTMLDirectoryElement],
	['dl', window.HTMLDListElement],
	// ['document', window.HTMLDocument],
	['fieldset', window.HTMLFieldSetElement],
	// ['frameset', window.HTMLFrameSetElement],
	['h1', window.HTMLHeadingElement],
	['h2', window.HTMLHeadingElement],
	['h3', window.HTMLHeadingElement],
	['h4', window.HTMLHeadingElement],
	['h5', window.HTMLHeadingElement],
	['h6', window.HTMLHeadingElement],
	['hr', window.HTMLHRElement],
	['iframe', window.HTMLIFrameElement],
	['img', window.HTMLImageElement],
	['ins', window.HTMLModElement],
	['li', window.HTMLLIElement],
	['menuitem', (window as any).HTMLMenuItemElement],
	['ol', window.HTMLOListElement],
	['optgroup', window.HTMLOptGroupElement],
	['p', window.HTMLParagraphElement],
	['q', window.HTMLQuoteElement],
	['tbody', window.HTMLTableSectionElement],
	['td', window.HTMLTableCellElement],
	['template', window.HTMLTemplateElement],
	['textarea', window.HTMLTextAreaElement],
	['tfoot', window.HTMLTableSectionElement],
	['th', window.HTMLTableCellElement],
	['thead', window.HTMLTableSectionElement],
	['tr', window.HTMLTableRowElement],
	['ul', window.HTMLUListElement],
	['vhgroupv', window.HTMLUnknownElement],
	['vkeygen', window.HTMLUnknownElement]
]);
