import { JS } from 'cellx';

export let elementConstructorMap = new JS.Map<string, typeof Element>([
	['a', (<any>window).HTMLAnchorElement],
	['blockquote', (<any>window).HTMLQuoteElement],
	['br', (<any>window).HTMLBRElement],
	['caption', (<any>window).HTMLTableCaptionElement],
	['col', (<any>window).HTMLTableColElement],
	['colgroup', (<any>window).HTMLTableColElement],
	['datalist', (<any>window).HTMLDataListElement],
	['del', (<any>window).HTMLModElement],
	['dir', (<any>window).HTMLDirectoryElement],
	['dl', (<any>window).HTMLDListElement],
	['document', (<any>window).HTMLDocument],
	['element', Element],
	['fieldset', (<any>window).HTMLFieldSetElement],
	['frameset', (<any>window).HTMLFrameSetElement],
	['h1', (<any>window).HTMLHeadingElement],
	['h2', (<any>window).HTMLHeadingElement],
	['h3', (<any>window).HTMLHeadingElement],
	['h4', (<any>window).HTMLHeadingElement],
	['h5', (<any>window).HTMLHeadingElement],
	['h6', (<any>window).HTMLHeadingElement],
	['hr', (<any>window).HTMLHRElement],
	['iframe', (<any>window).HTMLIFrameElement],
	['img', (<any>window).HTMLImageElement],
	['ins', (<any>window).HTMLModElement],
	['li', (<any>window).HTMLLIElement],
	['menuitem', (<any>window).HTMLMenuItemElement],
	['ol', (<any>window).HTMLOListElement],
	['optgroup', (<any>window).HTMLOptGroupElement],
	['p', (<any>window).HTMLParagraphElement],
	['q', (<any>window).HTMLQuoteElement],
	['tbody', (<any>window).HTMLTableSectionElement],
	['td', (<any>window).HTMLTableCellElement],
	['template', (<any>window).HTMLTemplateElement || HTMLElement],
	['textarea', (<any>window).HTMLTextAreaElement],
	['tfoot', (<any>window).HTMLTableSectionElement],
	['th', (<any>window).HTMLTableCellElement],
	['thead', (<any>window).HTMLTableSectionElement],
	['tr', (<any>window).HTMLTableRowElement],
	['ul', (<any>window).HTMLUListElement],
	['vhgroupv', (<any>window).HTMLUnknownElement],
	['vkeygen', (<any>window).HTMLUnknownElement]
]);
